### ISSUE TITLE
[Bug]: Potential crash when playing the Diamond Casino Heist after using the Heist Editor

### ISSUE THREAD

**Issue by hx12x12** [pierrelasse/YimStuff#4]
### What is the bug?

[DEBUG/script_function.cpp:36] found in RC Pause_multiplayer

the game pauses or doesnt respond then crash

### How to reproduce

setup diamond casino using this lua...
art
worst guns
best vehicles
normal mode
big con
5-5-3 % for team supliers
play
inv players
then while choosing entry to the casino (side, back, top etc)  the game pauses or doesnt respond

### How it should be

shuld not pause the game and then manu also doesnt respond

**Comment by pierrelasse** [comment]
1. Can you upload the log (cout.txt/log)
2. Are you stuck on a blackscreen? If yes, this is rockstars fault and many players have this super annoying issue

**Comment by hx12x12** [comment]
i crashed 3 time on exactly the same thing
no black screen gta gets stuck
then if i press a key program not responding / close it dialog comes


[cout.log](https://github.com/pierrelasse/YimStuff/files/13060713/cout.log)
at the very end of this file

[00:04:50.7880627][DEBUG/script_function.cpp:35] Found pattern RSD in script PauseMenu_Multiplayer

**Comment by hx12x12** [comment]
this line 
[00:04:50.7880627][DEBUG/script_function.cpp:35] Found pattern RSD in script PauseMenu_Multiplayer
appeared all 3 times when game was stuck/pause/crashed.... i checked

**Comment by pierrelasse** [comment]
Does this happen randomly?
If not you could you please try do this without the script to see if the script is the problem?

**Comment by hx12x12** [comment]
OK ill try and tell 
but yeah happened 3 times in a row. 
but 1 more thing i noticed when i was setting the appartment heist using this lua i applied changes and it notified that changes were applied to diamond casino heist.. that might be the problem i think.. i might be wrong but it catched my eye

**Comment by hx12x12** [comment]
if this happens again ill screenshot it

**Comment by hx12x12** [comment]
look i hit apply and this pops up in the right top corner
![Screenshot 2023-10-21 190206](https://github.com/pierrelasse/YimStuff/assets/138899842/63c1a6bd-2192-48db-8e4d-dfc4bbb338c5)

**Comment by pierrelasse** [comment]
> but 1 more thing i noticed when i was setting the appartment heist using this lua i applied changes and it notified that changes > were applied to diamond casino heist.. that might be the problem i think.. i might be wrong but it catched my eye
do you mean that in the notification it said 'Diamond Casino Heist'? If yes, i fixed it.

**Comment by hx12x12** [comment]
NOPE STILL CRASHING
![Screenshot 2023-10-21 190731](https://github.com/pierrelasse/YimStuff/assets/138899842/7fffb7f9-f44e-4a21-912c-6ebabada65a0)

THIS is the exact point of crash

**Comment by pierrelasse** [comment]
Intresting, have you tried without the script?

**Comment by hx12x12** [comment]
no ill try

**Comment by hx12x12** [comment]
yes crash without script... so this might mean it is not setting the heist right???
heist editor is doing fine in my opinion

**Comment by hx12x12** [comment]
i tried cayo with ur script it works fine... only this diamond one is having this bug

**Comment by pierrelasse** [comment]
If you crash without the script, then the script can't be directly the crashes fault.
You could try to use completly other settings for the heist and see if the crash still persists.
If the issue still persists, you could try unload the menu before the crash.
If you don't crash, you could to report it to YimMenu directly.

**Comment by hx12x12** [comment]
but the thing is i set it up using ur script thats why its crashing and when i use other editors like hesit editor latest version it wroks just fine..

**Comment by pierrelasse** [comment]
I was unable to reproduce the crash with these setings:
![image](https://github.com/pierrelasse/YimStuff/assets/76223390/e760d838-b8c2-4e13-9551-5efd8fea0406)
